# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0002_favorites_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='quoteby',
            field=models.CharField(default='Unkown', max_length=45),
        ),
        migrations.AddField(
            model_name='quotes',
            name='quoteby',
            field=models.CharField(default='Unkown', max_length=45),
        ),
    ]
